#!/bin/sh

set -e

git am --abort || true

git am ../patch/0001-riscv-Fix-build-against-binutils-2.38.patch

# sbi system reset
git am ../patch/0001-riscv-add-missing-SBI-extension-definitions.patch
git am ../patch/0001-sysreset-provide-SBI-based-sysreset-driver.patch

# sbi command
git am ../patch/0001-cmd-sbi-use-constants-instead-of-numerical-values.patch
git am ../patch/0001-riscv-function-to-retrieve-SBI-implementation-versio.patch
git am ../patch/0001-cmd-sbi-show-SBI-implementation-version.patch
git am ../patch/0001-riscv-provide-missing-base-extension-functions.patch
git am ../patch/0001-cmd-sbi-add-missing-SBI-information.patch
git am ../patch/0001-efi_loader-expose-the-device-tree-file-name.patch

git am ../patch/0001-disk-accessors-for-conditional-partition-fields.patch
git am ../patch/0001-kconfig-new-macro-OPT_ENABLED.patch
git am ../patch/0001-spl-allow-loading-via-partition-type-GUID.patch
